### ISSUE TITLE
Webinterface for the password-manager-resource

### ISSUE THREAD

**Issue by DerJuulsn** [DerJuulsn/password-manager-resources#4]

**Comment by DerJuulsn** [comment]
@cljazouli

**Comment by DerJuulsn** [comment]
Hey! So, I'm using Node.js locally to run a server via express to test the code. I'll shortly commit those things for you so you can work on it if you want. I've also created a second account (named password-manager-resources-bot) which I use to create the commits on for the pull requests.
I'll probably commit the code to a second branch there.

**Comment by DerJuulsn** [comment]
@clijazouli Btw, I'm currently wondering if we should use gh-pages to run the website, this would be super easy but I don't know if it works with Node. You've got any idea?

**Comment by cljazouli** [comment]
You should probably ask the repo maintainers.
